### PR TITLE
Improved Comments: Highlight Unread, Improve Nesting and Layout

### PR DESCRIPTION
**Pull request by aseckin**
This PR introduces a few tweaks and improvements to how Comments section is rendered.

- Unread comments are highlighted in purple.
- Nested comments use a different coloring logic
- Nested comments have tighter spacing in small screens
- Comments section is separated into its own container
- Better layout for the top part of the Comments section

image

### CODE REVIEW

**Review by ncarazon — APPROVED** [review]
lgtm

**Comment by aseckin** [comment]
thanks @ncarazon I'm having trouble deploying this for QA so will wait before merging

**Comment by aseckin** [comment]
@ncarazon Any objections to merging this? Sorry if the commit history got cluttered, since your last review there were a few changes
- Removed checkbox for private comments, and applied that functionality to the Public / Private feed toggle
- Hide comment buttons unless the user interacts with the markdown editor
- Some cosmetic improvements

**Review by ncarazon — COMMENTED** [review]
Seeing some issues on desktop and mobile:

Question where I was able to reproduce: http://localhost:3000/questions/29440/us-two-or-more-covid-19-waves-in-2028-and-2029/

image

image

**Comment by ncarazon** [comment]
@aseckin still looks broken for me on mobile:

image

**Comment by ncarazon** [comment]
> > @aseckin still looks broken for me on mobile:
> > image
> 
> Are you loading the page on desktop and then scaling it down? There is conditional rendering on the Changed My Mind button, which doesn't appear when if the screen size is small when the page is loading.
> 
> image

Oh, right. LGTM 👍

**Pull request merged**
