### PR TITLE
Update comments UI

### PR DESCRIPTION
**Pull request by EloiseRosen**
for https://github.com/Metaculus/metaculus/issues/924

notes:
* t("includeMyForecast") and t("privateComment") (the checkbox strings) aren't used anywhere else so this change won't change text somewhere else on the site
* I updated t("includeMyForecast") and t("privateComment") only for English. Should I delete the non-English versions in cs.json, es.json, zh.json since they're slightly different now? Not sure what your process is for updating translations.
* for logged out users, there will be no "([newCommentCount] new)" shown
* made newest/oldest/best in sort dropdown menu lower case as well

before:
comments_before

after:
comments_after

functionality:
https://drive.google.com/file/d/1yPZkEVAWSJdM1qM911M4-yAYjPpdXrKL/view?usp=sharing

### CODE REVIEW

**Comment by lsabor** [comment]
>I updated t("includeMyForecast") and t("privateComment") only for English. Should I delete the non-English versions in cs.json, es.json, zh.json since they're slightly different now? Not sure what your process is for updating translations.

I think the majority of translations had been done in the previous site by a service. I am actually unsure how it's done now.
@elisescu Can you comment on that?

The failing unit tests are likely my bad and just a linting issue. I'll push a quick fix and then you'll have to pull main again.

Otherwise, looks great to me.

**Comment by lsabor** [comment]
Worth looking into compatability of this PR with #1232 beyond just the variable name change causing the conflict.

**Comment by aseckin** [comment]
@EloiseRosen thanks a lot for this! Looks like we've been working on similar things in parallel - would it be OK if I deprecate this and we move over to [this PR](https://github.com/Metaculus/metaculus/pull/1232/)? Would love to get your input on the additional changes there.

**Comment by EloiseRosen** [comment]
@aseckin Absolutely!

**Pull request closed without merging**
