### PR TITLE
maybe fix #1222 - leaderboard links

### LINKED ISSUE #1222: Clicking question on Leaderboard leads to different question
## Current behavior
When I click on the second question on the AI Benchmarking Leaderboard (about the Yankees), I'm sent to a different question in a different tournament. 
Screenshot 2024-11-01 at 2 43 08 PM
Screenshot 2024-11-01 at 2 43 21 PM
Yankee question on this page: https://www.metaculus.com/tournament/aibq4/
Clicking sends me here: https://www.metaculus.com/questions/29028/

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

### PR DESCRIPTION
**Pull request by draaglom**
note that this is a 'sight read' based on the issue raised -- I don't know 100% that this is the fix and I **haven't tested it myself** because I can't load a tournament page locally without an openai api key

### CODE REVIEW

**Review by hlbmtc — APPROVED** [review]
Nice catch!

**Comment by hlbmtc** [comment]
Ah, sorry. I want @lsabor check this out because I'm not sure our backend propagates `Contribution.post_id` correctly

**Comment by draaglom** [comment]
it looks like it does, seems that we're just passing the raw fetch result about:

https://github.com/Metaculus/metaculus/blob/db8cd0aae31d6296174887060c7da6eacce9b55d/front_end/src/services/leaderboard.ts#L70-L79

https://github.com/Metaculus/metaculus/blob/db8cd0aae31d6296174887060c7da6eacce9b55d/front_end/src/app/(main)/(leaderboards)/contributions/components/project_contributions.tsx#L18

https://github.com/Metaculus/metaculus/blob/db8cd0aae31d6296174887060c7da6eacce9b55d/front_end/src/app/(main)/(leaderboards)/contributions/components/project_contributions.tsx#L54

(but I'll never say no to another pair of eyes on code that I'll stress I've not tested)

**Comment by draaglom** [comment]
closing in favour of #1225

**Comment by lsabor** [comment]
Correct on the front end.
I just noticed that unscored contributions were missing their relevant "post"

**Pull request closed without merging**
