### PR TITLE
Move download-csv to NextJS action

### PR DESCRIPTION
**Pull request by lsabor**
The previous version of this just opened a window that linked directly to the API, which lacked headers that allowed non-staff users to be logged in.
So I'm trying to have all the download csv actions handled in Next JS which will natively include the logged in user's authentication, but I can't seem to get it to work.
The response at the moment complains:
"""Error: Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported."""

Edit:
Thanks @ncarazon for all the help. Issues are sorted.

### CODE REVIEW

**Comment by lsabor** [comment]
@ncarazon I need some help on this one

**Comment by ncarazon** [comment]
@lsabor pushed a fix. Server action doesn't support returning complex objects like blob instance from server to client. I added a logic to convert the file into base64 string and then creating Blob in the client.

**Comment by lsabor** [comment]
@ncarazon Thanks for your help.
Can you help me debug why there is a failure to compile in testing?
https://github.com/Metaculus/metaculus/actions/runs/12380172678/job/34555931740?pr=1735

**Comment by ncarazon** [comment]
@lsabor pushed a fix. For some reason, type declaration for wasn't `file-saver` package wasn't missing when building in CI, while locally it worked perfectly fine. Maybe this is somehow related to caching (either of next builds or node modules). I've manually added type declarations to resolve the issue

**Review by ncarazon — APPROVED** [review]

**Pull request merged**
